name: Versionamiento Automático

on:
  pull_request:
    branches:
      - main
      - qa
      - develop

jobs:
  versionamiento:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Obtener rama de origen
        id: rama_origen
        run: |
          echo "Rama de origen: ${{ github.head_ref }}"

      - name: Obtener nombre de rama de origen
        id: nombre_rama_origen
        run: |
          echo "Nombre de rama de origen: ${{ github.head_ref.split('/')[1] }}"

      - name: Incrementar versión
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          npm version ${{(steps.nombre_rama_origen.outputs.nombre_rama_origen).startsWith('feat/') ? '-preminor' : (steps.nombre_rama_origen.outputs.nombre_rama_origen).startsWith('fix/') ? '-prepatch' : ''}}

      - name: Incrementar versión
        if: ${{ github.ref == 'refs/heads/qa' && github.base_ref == 'refs/heads/develop' }}
        run: |
          npm version ${{(steps.nombre_rama_origen.outputs.nombre_rama_origen).startsWith('feat/') ? '-minor' : (steps.nombre_rama_origen.outputs.nombre_rama_origen).startsWith('fix/') ? '-patch' : ''}}

      - name: Incrementar versión
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm version

      - name: Actualizar archivo package.json
        run: npm install

      - name: Crear commit
        run: |
          git add package.json
          git commit -m "Actualización de versión a $(npm version --no-git-tag)"

      - name: Push cambios
        run: git push
