name: Versionado Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Obtener versión actual
        id: get_version
        run: echo "::set-output name=version::$(npm version --no-git-tag)"

      - name: Aumentar versión preminor (adjust for your versioning strategy)
        run: npm version --preminor

      - name: Crear etiqueta
        run: |
          version=$(npm version --no-git-tag)
          tag="v${version%%#*}"
          git tag -m "Bump version to $tag" "$tag"

      - name: Actualizar versión en package.json
        run: npm version --no-git-tag

      - name: Commit y Push
        run: |
          git add .
          git commit -m "Bump version to $tag"
          git push origin develop
