name: Versionado Develop

on:
  pull_request:
    branches:
      - dev

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Obtener versión actual
        id: get_version
        run: echo "::set-output name=version::$(npm version --no-git-tag)"

      - name: Aumentar versión preminor
        run: npm version --preminor

      - name: Crear etiqueta
        run: git tag "v$(npm version --no-git-tag)"

      - name: Actualizar versión en package.json
        run: npm version --no-git-tag

      - name: Commit y Push
        run: |
          git add package.json
          git commit -m "Bump version to v$(npm version --no-git-tag)"
          git push origin dev
