name: Versionado Develop

on:
  pull_request:
    branches:
      - dev

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Obtain current version
        id: get_version
        run: echo "::set-output name=version::$(npm version --no-git-tag)"

      - name: Increase preminor version (adjust for your versioning strategy)
        run: npm version --preminor

      - name: Create tag
        run: |
          version=$(npm version --no-git-tag)
          tag="v${version%%#*}"
          git tag -m "Bump version to $tag" "$tag"

      - name: Update version in package.json
        run: npm version --no-git-tag

      - name: Commit and Push
        run: |
          git add package.json
          git commit -m "Bump version to $tag"
          git push origin dev
